#-------------------------------
# Site Settings
title: smokentar
description: TechGymOps
color_scheme: dark # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "/images/cover.svg" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Resources'
      url: '/resources/'
    - title: 'Changelog'
      url: '/changelog/'
    - title: 'Search'
      url: '/tags/'


#-------------------------------
# Author Settings
author:
  author_name: Dimitar Atanasov
  author_role: DevOps & Security
  author_bio: | 
    An engineer with half a decade of experience in Cloud Operations and Automation, specializing in the creation and maintenance of secure and reliable infrastructure. 
    In the physical world he repetitively lifts heavy things and puts them back down.

  author_avatar: '/images/avatar.jpeg'
  cta_button_text: Get In Touch
  cta_button_link: '/contact/'


#-------------------------------
# Projects Settings
projects_settings:
  enable: true
  projects_title: Projects
  projects_description:


#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Testimonials
  testimonials_description:

testimonial_items:
  - name: "Foo Bar"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    content : "Future testimonial"

  - name: "Bar Foo"
    image: "/images/client-2.jpg"
    designation: "DevOps Engineer"
    content : "Future testimonial"

  - name: "Far Boo"
    image: "/images/client-3.jpg"
    designation: "Systems Analyst"
    content : "Future testimonial"


#-------------------------------
# Blog Section
blog_settings:
  enable: true
  blog_title: Resources
  blog_description:


#-------------------------------
# Videos Settings
videos_settings:
  enable: false
  videos_title: Videos
  videos_description:


#-------------------------------
# Gallery Section
gallery_settings:
  enable: false
  gallery_title: Gallery
  gallery_description:


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_identifier: placeholder # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to my newsletter and I'll send you dopamine-infused tech articles.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Me # Add your button text


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/smokentar"}
- {icon: "fa-brands fa-linkedin", name: "Linkedin", link: "https://www.linkedin.com/in/dimatt/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: meojjqer # Formspree id
  description: Feel free to reach out to me for any queries or suggestions. I'm always open to new opportunities and collaborations.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id